id: b96f3a9d0b294c8cb769450f2a77832d
initial_creation_type: ocr
source_metadata:
  volumes:
    9ce9f45c4c20471c93d1ca4edc2b2d1f:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: གྲུབ་ཐོབ་ལྔ་བཅུའི་རྟོགས་པ་བརྗོད་པ་ཐིག་ལེ་འོད་ཀྱི་ཕྲེང་བ།
      total_pages: 1953
      volume_number: 27
